#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("hastane.Resource", IsApplication=true)]

namespace hastane
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Me.ITheBK.Resource.Attribute.bar_color = global::hastane.Resource.Attribute.bar_color;
			global::Me.ITheBK.Resource.Attribute.bar_max_value = global::hastane.Resource.Attribute.bar_max_value;
			global::Me.ITheBK.Resource.Attribute.bar_show_animation = global::hastane.Resource.Attribute.bar_show_animation;
			global::Me.ITheBK.Resource.Attribute.bar_show_auto_color = global::hastane.Resource.Attribute.bar_show_auto_color;
			global::Me.ITheBK.Resource.Attribute.bar_show_value = global::hastane.Resource.Attribute.bar_show_value;
			global::Me.ITheBK.Resource.Attribute.bar_spaces = global::hastane.Resource.Attribute.bar_spaces;
			global::Me.ITheBK.Resource.Attribute.bar_text_color = global::hastane.Resource.Attribute.bar_text_color;
			global::Me.ITheBK.Resource.Attribute.bar_text_size = global::hastane.Resource.Attribute.bar_text_size;
			global::Me.ITheBK.Resource.Attribute.bar_type = global::hastane.Resource.Attribute.bar_type;
			global::Me.ITheBK.Resource.Attribute.bar_width = global::hastane.Resource.Attribute.bar_width;
			global::Me.ITheBK.Resource.Id.horizontal = global::hastane.Resource.Id.horizontal;
			global::Me.ITheBK.Resource.Id.linear_bar = global::hastane.Resource.Id.linear_bar;
			global::Me.ITheBK.Resource.Id.tv_bar = global::hastane.Resource.Id.tv_bar;
			global::Me.ITheBK.Resource.Id.vertical = global::hastane.Resource.Id.vertical;
			global::Me.ITheBK.Resource.Layout.bar_horizontal = global::hastane.Resource.Layout.bar_horizontal;
			global::Me.ITheBK.Resource.Layout.bar_vertical = global::hastane.Resource.Layout.bar_vertical;
			global::Me.ITheBK.Resource.String.app_name = global::hastane.Resource.String.app_name;
			global::Me.ITheBK.Resource.Styleable.BarChart = global::hastane.Resource.Styleable.BarChart;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_color = global::hastane.Resource.Styleable.BarChart_bar_color;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_max_value = global::hastane.Resource.Styleable.BarChart_bar_max_value;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_show_animation = global::hastane.Resource.Styleable.BarChart_bar_show_animation;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_show_auto_color = global::hastane.Resource.Styleable.BarChart_bar_show_auto_color;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_show_value = global::hastane.Resource.Styleable.BarChart_bar_show_value;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_spaces = global::hastane.Resource.Styleable.BarChart_bar_spaces;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_text_color = global::hastane.Resource.Styleable.BarChart_bar_text_color;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_text_size = global::hastane.Resource.Styleable.BarChart_bar_text_size;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_type = global::hastane.Resource.Styleable.BarChart_bar_type;
			global::Me.ITheBK.Resource.Styleable.BarChart_bar_width = global::hastane.Resource.Styleable.BarChart_bar_width;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int planets_array = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int planets_arrayy = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int planets_arrayyy = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int planets_arrayyyy = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int bar_color = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int bar_max_value = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int bar_show_animation = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int bar_show_auto_color = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int bar_show_value = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int bar_spaces = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int bar_text_color = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int bar_text_size = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int bar_type = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int bar_width = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonstyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int main = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060024
			public const int anasyf = 2131099684;
			
			// aapt resource value: 0x7f06001c
			public const int bad = 2131099676;
			
			// aapt resource value: 0x7f060002
			public const int barChartView1 = 2131099650;
			
			// aapt resource value: 0x7f06001f
			public const int bdgmyl = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int bdoktor = 2131099682;
			
			// aapt resource value: 0x7f060020
			public const int bplklnk = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int bsaat = 2131099683;
			
			// aapt resource value: 0x7f06001e
			public const int bsoyad = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int btarih = 2131099681;
			
			// aapt resource value: 0x7f06001a
			public const int btc = 2131099674;
			
			// aapt resource value: 0x7f060016
			public const int dgmyl = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int giris = 2131099671;
			
			// aapt resource value: 0x7f060003
			public const int grgt1 = 2131099651;
			
			// aapt resource value: 0x7f06002f
			public const int grgt2 = 2131099695;
			
			// aapt resource value: 0x7f060014
			public const int grgt3 = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int horizontal = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int kadi = 2131099658;
			
			// aapt resource value: 0x7f060018
			public const int kayit = 2131099672;
			
			// aapt resource value: 0x7f060010
			public const int kdgmyl = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int kdgmyr = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int kkayitol = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int ksoyad = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int ktc = 2131099662;
			
			// aapt resource value: 0x7f06002e
			public const int linearLayout1 = 2131099694;
			
			// aapt resource value: 0x7f060007
			public const int linear_bar = 2131099655;
			
			// aapt resource value: 0x7f060026
			public const int rad = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int rdgmyl = 2131099688;
			
			// aapt resource value: 0x7f060004
			public const int rndval = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int rndviptal = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int rndvsrgla = 2131099653;
			
			// aapt resource value: 0x7f06002d
			public const int ronayla = 2131099693;
			
			// aapt resource value: 0x7f060027
			public const int rsoyad = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int rtc = 2131099685;
			
			// aapt resource value: 0x7f060029
			public const int spinner = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int spinnerr = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int spinnerrr = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int spinnerrrr = 2131099692;
			
			// aapt resource value: 0x7f060015
			public const int tcNo = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int textView16 = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int textView3 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int textView5 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int textView7 = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int tv_bar = 2131099656;
			
			// aapt resource value: 0x7f060019
			public const int txtView1 = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int txtView3 = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int txtView5 = 2131099677;
			
			// aapt resource value: 0x7f060001
			public const int vertical = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int analiz = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int anasayfa = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bar_horizontal = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int bar_vertical = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int kayit = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int rbilgi = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int rgrntl = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int rndval = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int rndviptal = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int rndvsrgl = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int saatanaliz = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Hello = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int planet_prompt = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int planet_promptt = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int planet_prompttt = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int planet_promptttt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BarChart = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public const int BarChart_bar_color = 1;
			
			// aapt resource value: 6
			public const int BarChart_bar_max_value = 6;
			
			// aapt resource value: 9
			public const int BarChart_bar_show_animation = 9;
			
			// aapt resource value: 5
			public const int BarChart_bar_show_auto_color = 5;
			
			// aapt resource value: 8
			public const int BarChart_bar_show_value = 8;
			
			// aapt resource value: 7
			public const int BarChart_bar_spaces = 7;
			
			// aapt resource value: 4
			public const int BarChart_bar_text_color = 4;
			
			// aapt resource value: 3
			public const int BarChart_bar_text_size = 3;
			
			// aapt resource value: 0
			public const int BarChart_bar_type = 0;
			
			// aapt resource value: 2
			public const int BarChart_bar_width = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
